### ISSUE TITLE
Waitinf for input K

### ISSUE THREAD

**Issue by YongxiangLei** [unstable-zeros/robust-mpc-sls#1]
Hi Shaoru,

When I run the case in the Dobule_integrator_example, there is a process that needs to manually input K? Could you give me some idea on how to fix this issue? Thanks in advance.

Yong

**Comment by ShaoruChen** [comment]
Hi Yong, 

Could you please point me to the specific file that gave you this error? As far as I can see, there is no need to manually give a feedback controller K anywhere. 

Thanks,
Shaoru

**Comment by YongxiangLei** [comment]
Hi Shaoru,

Really thanks for your kind response.

When I try to reproduce the results,  When I run the main_DI_coarseSLS_feasibilitycheck.m, the got a isFeasible = 0, such as:

![123](https://user-images.githubusercontent.com/28838060/213754502-8f6aa86a-6938-418e-94bc-514b12bdb277.png)

and then 

![image](https://user-images.githubusercontent.com/28838060/213755243-f46202c3-b50d-4f44-9595-8f17936a59b3.png)

I thought the system state had dropped to an infeasible area. When I try to debug the code, the tau lower boundary is bigger than the upper boundary, which causes the infeasible solution.

I would be so grateful if you can help.

Thanks,
Yong

**Comment by ShaoruChen** [comment]
Hi Yong,

Thanks for your detailed reply. It seems you encountered infeasibility of the hyperparameter search in the function Evaluate_CoarseSLSMPC() in [Line 13](https://github.com/unstable-zeros/robust-mpc-sls/blob/7e77bb376498a9864768fd92dfa45638bc356efc/Double_integrator_example/main_DI_coarseSLS_feasibilitycheck.m#L13) of main_DI_coarseSLS_feasibilitycheck.m. This means for the currently given initial state, the search for hyperparameters has failed and the program enters the debug mode (that's why you see K>> in the command line. See https://www.mathworks.com/matlabcentral/answers/283542-how-do-i-get-rid-of-the-k-prompt). In this case, you can provide another initial state x0, probably close to the origin, and rerun the script. 

The main purpose of the codes from line 13 to line 16 in main_DI_coarseSLS_feasibilitycheck.m is to compute the lower bound on tau, which is actually independent of the initial state and can be reused in evaluating the feasible domain of coarse SLS MPC over a grid of initial conditions. So another solution is to manually record the lower bound on tau as X when you encountered infeasibility in Evaluate_CoarseSLSMPC(), and rerun main_DI_coarseSLS_feasibilitycheck.m by skipping [line 13](https://github.com/unstable-zeros/robust-mpc-sls/blob/7e77bb376498a9864768fd92dfa45638bc356efc/Double_integrator_example/main_DI_coarseSLS_feasibilitycheck.m#L13) and set bisect_opt.init.tau.lb = X in [line 43](https://github.com/unstable-zeros/robust-mpc-sls/blob/7e77bb376498a9864768fd92dfa45638bc356efc/Double_integrator_example/main_DI_coarseSLS_feasibilitycheck.m#L43). 

Best,
Shaoru

**Comment by YongxiangLei** [comment]
Hi Shaoru, 

Thank you so much, it works quite well now.

Best regards,
Yong
